{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 11): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 13): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 14): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 16): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 17): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 18): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 19): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 20): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 21): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 22): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 23): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 24): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 25): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 26): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 27): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 28): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 29): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 30): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 31): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 32): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 33): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 34): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 35): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 36): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 37): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 38): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 39): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 40): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 41): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 42): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 43): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 44): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 45): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 46): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 47): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 48): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 49): Error: Trying to open unclosed connection.","timestamp":"8:58:28 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 50): Error: Trying to open unclosed connection.","timestamp":"8:58:29 AM"}
{"level":"error","message":"(node:14108) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 51): Error: Trying to open unclosed connection.","timestamp":"8:58:29 AM"}
{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"9:01:04 AM"}
{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"10:43:57 AM"}
{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"10:44:07 AM"}
{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"10:44:25 AM"}
{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"10:44:30 AM"}
{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"10:45:10 AM"}
{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"12:44:04 PM"}
{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"12:44:56 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"12:53:33 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"12:53:33 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"12:53:34 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"12:53:34 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"12:53:34 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"12:53:34 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"12:53:34 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"12:53:35 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"12:53:35 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"12:53:35 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"12:53:36 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"12:53:36 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"12:53:36 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"12:53:36 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"12:53:36 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"12:53:36 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"12:53:36 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"12:53:36 PM"}
{"level":"warn","message":"uncaughtException { DisconnectedError: Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.\n    at MongooseError.DisconnectedError (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\error\\disconnected.js:21:11)\n    at Server.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\connection.js:64:31)\n    at emitOne (events.js:101:20)\n    at Server.emit (events.js:188:7)\n    at Pool.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:319:16)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:188:7)\n    at Connection.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\pool.js:309:16)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:191:7)\n    at Socket.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\connection\\connection.js:177:49)\n    at Socket.g (events.js:291:16)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at emitErrorNT (net.js:1278:8)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n  message: 'Ran out of retries trying to reconnect to \"3.109.206.238:27017\". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',\n  name: 'DisconnectedError' }","timestamp":"12:53:37 PM"}
{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"2:29:14 PM"}
{"level":"warn","message":"uncaughtException { MongoError: server instance pool was destroyed\n    at Function.MongoError.create (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\error.js:29:11)\n    at basicWriteValidations (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:449:51)\n    at Server.insert (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:541:16)\n    at Server.insert (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\server.js:385:17)\n    at executeBatch (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\bulk\\unordered.js:433:23)\n    at executeBatches (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\bulk\\unordered.js:453:5)\n    at UnorderedBulkOperation.execute (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\bulk\\unordered.js:511:44)\n    at bulkWrite (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\collection.js:664:8)\n    at Collection.insertMany (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\collection.js:534:44)\n    at Collection.insert (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\collection.js:836:15)\n    at NativeCollection.(anonymous function) [as insert] (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:126:28)\n    at model.Model.$__handleSave (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\model.js:142:21)\n    at model.Model.$__save (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\model.js:213:9)\n    at model.Model.save (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\model.js:321:15)\n    at model._done (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:101:24)\n    at _next (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:64:28)\n    at fnWrapper (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:186:8)\n    at model.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\plugins\\saveSubdocs.js:22:7)\n    at _next (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:62:30)\n    at fnWrapper (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:186:8)\n    at D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\plugins\\validateBeforeSave.js:35:13\n    at D:\\Admin\\SourceCode\\node_modules\\kareem\\index.js:131:16\n  name: 'MongoError',\n  message: 'server instance pool was destroyed' }","timestamp":"2:29:14 PM"}
{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"4:35:15 PM"}
{"level":"warn","message":"uncaughtException { MongoError: server instance pool was destroyed\n    at Function.MongoError.create (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\error.js:29:11)\n    at basicWriteValidations (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:449:51)\n    at Server.insert (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:541:16)\n    at Server.insert (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\server.js:385:17)\n    at executeBatch (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\bulk\\unordered.js:433:23)\n    at executeBatches (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\bulk\\unordered.js:453:5)\n    at UnorderedBulkOperation.execute (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\bulk\\unordered.js:511:44)\n    at bulkWrite (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\collection.js:664:8)\n    at Collection.insertMany (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\collection.js:534:44)\n    at Collection.insert (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\collection.js:836:15)\n    at NativeCollection.(anonymous function) [as insert] (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:126:28)\n    at model.Model.$__handleSave (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\model.js:142:21)\n    at model.Model.$__save (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\model.js:213:9)\n    at model.Model.save (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\model.js:321:15)\n    at model._done (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:101:24)\n    at _next (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:64:28)\n    at fnWrapper (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:186:8)\n    at model.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\plugins\\saveSubdocs.js:22:7)\n    at _next (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:62:30)\n    at fnWrapper (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:186:8)\n    at D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\plugins\\validateBeforeSave.js:35:13\n    at D:\\Admin\\SourceCode\\node_modules\\kareem\\index.js:131:16\n  name: 'MongoError',\n  message: 'server instance pool was destroyed' }","timestamp":"4:35:15 PM"}
{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"4:35:25 PM"}
{"level":"warn","message":"uncaughtException { MongoError: server instance pool was destroyed\n    at Function.MongoError.create (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\error.js:29:11)\n    at basicWriteValidations (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:449:51)\n    at Server.insert (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:541:16)\n    at Server.insert (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\server.js:385:17)\n    at executeBatch (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\bulk\\unordered.js:433:23)\n    at executeBatches (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\bulk\\unordered.js:453:5)\n    at UnorderedBulkOperation.execute (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\bulk\\unordered.js:511:44)\n    at bulkWrite (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\collection.js:664:8)\n    at Collection.insertMany (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\collection.js:534:44)\n    at Collection.insert (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\collection.js:836:15)\n    at NativeCollection.(anonymous function) [as insert] (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:126:28)\n    at model.Model.$__handleSave (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\model.js:142:21)\n    at model.Model.$__save (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\model.js:213:9)\n    at model.Model.save (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\model.js:321:15)\n    at model._done (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:101:24)\n    at _next (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:64:28)\n    at fnWrapper (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:186:8)\n    at model.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\plugins\\saveSubdocs.js:22:7)\n    at _next (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:62:30)\n    at fnWrapper (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:186:8)\n    at D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\plugins\\validateBeforeSave.js:35:13\n    at D:\\Admin\\SourceCode\\node_modules\\kareem\\index.js:131:16\n  name: 'MongoError',\n  message: 'server instance pool was destroyed' }","timestamp":"4:35:25 PM"}
{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"6:15:29 PM"}
{"level":"warn","message":"uncaughtException { MongoError: server instance pool was destroyed\n    at Function.MongoError.create (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\error.js:29:11)\n    at basicWriteValidations (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:449:51)\n    at Server.insert (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:541:16)\n    at Server.insert (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\server.js:385:17)\n    at executeBatch (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\bulk\\unordered.js:433:23)\n    at executeBatches (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\bulk\\unordered.js:453:5)\n    at UnorderedBulkOperation.execute (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\bulk\\unordered.js:511:44)\n    at bulkWrite (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\collection.js:664:8)\n    at Collection.insertMany (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\collection.js:534:44)\n    at Collection.insert (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\collection.js:836:15)\n    at NativeCollection.(anonymous function) [as insert] (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:126:28)\n    at model.Model.$__handleSave (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\model.js:142:21)\n    at model.Model.$__save (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\model.js:213:9)\n    at model.Model.save (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\model.js:321:15)\n    at model._done (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:101:24)\n    at _next (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:64:28)\n    at fnWrapper (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:186:8)\n    at model.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\plugins\\saveSubdocs.js:22:7)\n    at _next (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:62:30)\n    at fnWrapper (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:186:8)\n    at D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\plugins\\validateBeforeSave.js:35:13\n    at D:\\Admin\\SourceCode\\node_modules\\kareem\\index.js:131:16\n  name: 'MongoError',\n  message: 'server instance pool was destroyed' }","timestamp":"6:15:30 PM"}
{"level":"error","message":"LOG REFERER YTD undefined ::ffff:127.0.0.1 undefined","timestamp":"6:15:52 PM"}
{"level":"warn","message":"uncaughtException { MongoError: server instance pool was destroyed\n    at Function.MongoError.create (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\error.js:29:11)\n    at basicWriteValidations (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:449:51)\n    at Server.insert (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb-core\\lib\\topologies\\server.js:541:16)\n    at Server.insert (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\server.js:385:17)\n    at executeBatch (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\bulk\\unordered.js:433:23)\n    at executeBatches (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\bulk\\unordered.js:453:5)\n    at UnorderedBulkOperation.execute (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\bulk\\unordered.js:511:44)\n    at bulkWrite (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\collection.js:664:8)\n    at Collection.insertMany (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\collection.js:534:44)\n    at Collection.insert (D:\\Admin\\SourceCode\\node_modules\\mongoose\\node_modules\\mongodb\\lib\\collection.js:836:15)\n    at NativeCollection.(anonymous function) [as insert] (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\drivers\\node-mongodb-native\\collection.js:126:28)\n    at model.Model.$__handleSave (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\model.js:142:21)\n    at model.Model.$__save (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\model.js:213:9)\n    at model.Model.save (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\model.js:321:15)\n    at model._done (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:101:24)\n    at _next (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:64:28)\n    at fnWrapper (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:186:8)\n    at model.<anonymous> (D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\plugins\\saveSubdocs.js:22:7)\n    at _next (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:62:30)\n    at fnWrapper (D:\\Admin\\SourceCode\\node_modules\\hooks-fixed\\hooks.js:186:8)\n    at D:\\Admin\\SourceCode\\node_modules\\mongoose\\lib\\plugins\\validateBeforeSave.js:35:13\n    at D:\\Admin\\SourceCode\\node_modules\\kareem\\index.js:131:16\n  name: 'MongoError',\n  message: 'server instance pool was destroyed' }","timestamp":"6:15:52 PM"}
